<?php
/**
 * AccountingV2InvoiceUpdateRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Jonathon Hill, CompWright Enterprises LLC (https://compwright.com)
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CompWright\ServiceTitan\Model;

use \ArrayAccess;
use \CompWright\ServiceTitan\ObjectSerializer;

/**
 * AccountingV2InvoiceUpdateRequest Class Doc Comment
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AccountingV2InvoiceUpdateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Accounting.V2.InvoiceUpdateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'number' => 'string',
        'type_id' => 'int',
        'invoiced_on' => '\DateTime',
        'subtotal' => 'float',
        'tax' => 'float',
        'summary' => 'string',
        'royalty_status' => 'OneOfAccountingV2RoyaltyStatus',
        'royalty_date' => '\DateTime',
        'royalty_sent_on' => '\DateTime',
        'royalty_memo' => 'string',
        'export_id' => 'string',
        'items' => '\CompWright\ServiceTitan\Model\AccountingV2InvoiceItemUpdateRequest[]',
        'payments' => '\CompWright\ServiceTitan\Model\AccountingV2PaymentSettlementUpdateRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'number' => null,
        'type_id' => 'int64',
        'invoiced_on' => 'date-time',
        'subtotal' => 'decimal',
        'tax' => 'decimal',
        'summary' => null,
        'royalty_status' => null,
        'royalty_date' => 'date-time',
        'royalty_sent_on' => 'date-time',
        'royalty_memo' => null,
        'export_id' => null,
        'items' => null,
        'payments' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'number' => 'number',
        'type_id' => 'typeId',
        'invoiced_on' => 'invoicedOn',
        'subtotal' => 'subtotal',
        'tax' => 'tax',
        'summary' => 'summary',
        'royalty_status' => 'royaltyStatus',
        'royalty_date' => 'royaltyDate',
        'royalty_sent_on' => 'royaltySentOn',
        'royalty_memo' => 'royaltyMemo',
        'export_id' => 'exportId',
        'items' => 'items',
        'payments' => 'payments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'number' => 'setNumber',
        'type_id' => 'setTypeId',
        'invoiced_on' => 'setInvoicedOn',
        'subtotal' => 'setSubtotal',
        'tax' => 'setTax',
        'summary' => 'setSummary',
        'royalty_status' => 'setRoyaltyStatus',
        'royalty_date' => 'setRoyaltyDate',
        'royalty_sent_on' => 'setRoyaltySentOn',
        'royalty_memo' => 'setRoyaltyMemo',
        'export_id' => 'setExportId',
        'items' => 'setItems',
        'payments' => 'setPayments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'number' => 'getNumber',
        'type_id' => 'getTypeId',
        'invoiced_on' => 'getInvoicedOn',
        'subtotal' => 'getSubtotal',
        'tax' => 'getTax',
        'summary' => 'getSummary',
        'royalty_status' => 'getRoyaltyStatus',
        'royalty_date' => 'getRoyaltyDate',
        'royalty_sent_on' => 'getRoyaltySentOn',
        'royalty_memo' => 'getRoyaltyMemo',
        'export_id' => 'getExportId',
        'items' => 'getItems',
        'payments' => 'getPayments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['number'] = $data['number'] ?? null;
        $this->container['type_id'] = $data['type_id'] ?? null;
        $this->container['invoiced_on'] = $data['invoiced_on'] ?? null;
        $this->container['subtotal'] = $data['subtotal'] ?? null;
        $this->container['tax'] = $data['tax'] ?? null;
        $this->container['summary'] = $data['summary'] ?? null;
        $this->container['royalty_status'] = $data['royalty_status'] ?? null;
        $this->container['royalty_date'] = $data['royalty_date'] ?? null;
        $this->container['royalty_sent_on'] = $data['royalty_sent_on'] ?? null;
        $this->container['royalty_memo'] = $data['royalty_memo'] ?? null;
        $this->container['export_id'] = $data['export_id'] ?? null;
        $this->container['items'] = $data['items'] ?? null;
        $this->container['payments'] = $data['payments'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets number
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string|null $number number
     *
     * @return self
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets type_id
     *
     * @return int|null
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     *
     * @param int|null $type_id type_id
     *
     * @return self
     */
    public function setTypeId($type_id)
    {
        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets invoiced_on
     *
     * @return \DateTime|null
     */
    public function getInvoicedOn()
    {
        return $this->container['invoiced_on'];
    }

    /**
     * Sets invoiced_on
     *
     * @param \DateTime|null $invoiced_on invoiced_on
     *
     * @return self
     */
    public function setInvoicedOn($invoiced_on)
    {
        $this->container['invoiced_on'] = $invoiced_on;

        return $this;
    }

    /**
     * Gets subtotal
     *
     * @return float|null
     */
    public function getSubtotal()
    {
        return $this->container['subtotal'];
    }

    /**
     * Sets subtotal
     *
     * @param float|null $subtotal subtotal
     *
     * @return self
     */
    public function setSubtotal($subtotal)
    {
        $this->container['subtotal'] = $subtotal;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return float|null
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param float|null $tax tax
     *
     * @return self
     */
    public function setTax($tax)
    {
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string|null $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets royalty_status
     *
     * @return OneOfAccountingV2RoyaltyStatus|null
     */
    public function getRoyaltyStatus()
    {
        return $this->container['royalty_status'];
    }

    /**
     * Sets royalty_status
     *
     * @param OneOfAccountingV2RoyaltyStatus|null $royalty_status royalty_status
     *
     * @return self
     */
    public function setRoyaltyStatus($royalty_status)
    {
        $this->container['royalty_status'] = $royalty_status;

        return $this;
    }

    /**
     * Gets royalty_date
     *
     * @return \DateTime|null
     */
    public function getRoyaltyDate()
    {
        return $this->container['royalty_date'];
    }

    /**
     * Sets royalty_date
     *
     * @param \DateTime|null $royalty_date royalty_date
     *
     * @return self
     */
    public function setRoyaltyDate($royalty_date)
    {
        $this->container['royalty_date'] = $royalty_date;

        return $this;
    }

    /**
     * Gets royalty_sent_on
     *
     * @return \DateTime|null
     */
    public function getRoyaltySentOn()
    {
        return $this->container['royalty_sent_on'];
    }

    /**
     * Sets royalty_sent_on
     *
     * @param \DateTime|null $royalty_sent_on royalty_sent_on
     *
     * @return self
     */
    public function setRoyaltySentOn($royalty_sent_on)
    {
        $this->container['royalty_sent_on'] = $royalty_sent_on;

        return $this;
    }

    /**
     * Gets royalty_memo
     *
     * @return string|null
     */
    public function getRoyaltyMemo()
    {
        return $this->container['royalty_memo'];
    }

    /**
     * Sets royalty_memo
     *
     * @param string|null $royalty_memo royalty_memo
     *
     * @return self
     */
    public function setRoyaltyMemo($royalty_memo)
    {
        $this->container['royalty_memo'] = $royalty_memo;

        return $this;
    }

    /**
     * Gets export_id
     *
     * @return string|null
     */
    public function getExportId()
    {
        return $this->container['export_id'];
    }

    /**
     * Sets export_id
     *
     * @param string|null $export_id export_id
     *
     * @return self
     */
    public function setExportId($export_id)
    {
        $this->container['export_id'] = $export_id;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \CompWright\ServiceTitan\Model\AccountingV2InvoiceItemUpdateRequest[]|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \CompWright\ServiceTitan\Model\AccountingV2InvoiceItemUpdateRequest[]|null $items items
     *
     * @return self
     */
    public function setItems($items)
    {
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets payments
     *
     * @return \CompWright\ServiceTitan\Model\AccountingV2PaymentSettlementUpdateRequest[]|null
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param \CompWright\ServiceTitan\Model\AccountingV2PaymentSettlementUpdateRequest[]|null $payments payments
     *
     * @return self
     */
    public function setPayments($payments)
    {
        $this->container['payments'] = $payments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


