<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace CompWright\ServiceTitan\Model;

class AccountingV2GLAccountResponse
{
    /**
     * @var string|null
     */
    protected $name;
    /**
     * @var string|null
     */
    protected $number;
    /**
     * @var string|null
     */
    protected $type;
    /**
     * @var string|null
     */
    protected $detailType;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDetailType(): ?string
    {
        return $this->detailType;
    }

    public function setDetailType(?string $detailType): self
    {
        $this->detailType = $detailType;

        return $this;
    }
}
