<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace CompWright\ServiceTitan\Model;

class AccountingV2InventoryBillItemResponse
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $order;
    /**
     * @var string|null
     */
    protected $name;
    /**
     * @var string|null
     */
    protected $description;
    /**
     * @var string|null
     */
    protected $quantity;
    /**
     * @var string|null
     */
    protected $cost;
    /**
     * @var string|null
     */
    protected $inventoryLocation;
    /**
     * @var string|null
     */
    protected $serialNumber;
    /**
     * @var mixed|null
     */
    protected $generalLedgerAccount;
    /**
     * @var mixed|null
     */
    protected $costOfSaleAccount;
    /**
     * @var mixed|null
     */
    protected $assetAccount;

    public function getOrder(): int
    {
        return $this->order;
    }

    public function setOrder(int $order): self
    {
        $this->initialized['order'] = true;
        $this->order = $order;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(?string $quantity): self
    {
        $this->initialized['quantity'] = true;
        $this->quantity = $quantity;

        return $this;
    }

    public function getCost(): ?string
    {
        return $this->cost;
    }

    public function setCost(?string $cost): self
    {
        $this->initialized['cost'] = true;
        $this->cost = $cost;

        return $this;
    }

    public function getInventoryLocation(): ?string
    {
        return $this->inventoryLocation;
    }

    public function setInventoryLocation(?string $inventoryLocation): self
    {
        $this->initialized['inventoryLocation'] = true;
        $this->inventoryLocation = $inventoryLocation;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serialNumber;
    }

    public function setSerialNumber(?string $serialNumber): self
    {
        $this->initialized['serialNumber'] = true;
        $this->serialNumber = $serialNumber;

        return $this;
    }

    public function getGeneralLedgerAccount()
    {
        return $this->generalLedgerAccount;
    }

    public function setGeneralLedgerAccount($generalLedgerAccount): self
    {
        $this->initialized['generalLedgerAccount'] = true;
        $this->generalLedgerAccount = $generalLedgerAccount;

        return $this;
    }

    public function getCostOfSaleAccount()
    {
        return $this->costOfSaleAccount;
    }

    public function setCostOfSaleAccount($costOfSaleAccount): self
    {
        $this->initialized['costOfSaleAccount'] = true;
        $this->costOfSaleAccount = $costOfSaleAccount;

        return $this;
    }

    public function getAssetAccount()
    {
        return $this->assetAccount;
    }

    public function setAssetAccount($assetAccount): self
    {
        $this->initialized['assetAccount'] = true;
        $this->assetAccount = $assetAccount;

        return $this;
    }
}
