<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace CompWright\ServiceTitan\Model;

class CrmV2JobTypeResponse
{
    /**
     * ID of the job type.
     *
     * @var int
     */
    protected $id;
    /**
     * Name of the job type.
     *
     * @var string
     */
    protected $name;
    /**
     * Date/time (in UTC) when job type was last modified.
     *
     * @var \DateTime
     */
    protected $modifiedOn;
    /**
     * List of external data attached to this job type,.
     *
     * @var CrmV2ExternalDataModel[]
     */
    protected $externalData;

    /**
     * ID of the job type.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * ID of the job type.
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Name of the job type.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Name of the job type.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Date/time (in UTC) when job type was last modified.
     */
    public function getModifiedOn(): \DateTime
    {
        return $this->modifiedOn;
    }

    /**
     * Date/time (in UTC) when job type was last modified.
     */
    public function setModifiedOn(\DateTime $modifiedOn): self
    {
        $this->modifiedOn = $modifiedOn;

        return $this;
    }

    /**
     * List of external data attached to this job type,.
     *
     * @return CrmV2ExternalDataModel[]
     */
    public function getExternalData(): array
    {
        return $this->externalData;
    }

    /**
     * List of external data attached to this job type,.
     *
     * @param CrmV2ExternalDataModel[] $externalData
     */
    public function setExternalData(array $externalData): self
    {
        $this->externalData = $externalData;

        return $this;
    }
}
