<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace CompWright\ServiceTitan\Model;

class CrmV2CancelReasonResponse
{
    /**
     * Job ID.
     *
     * @var int
     */
    protected $jobId;
    /**
     * ID of the reason.
     *
     * @var int
     */
    protected $reasonId;
    /**
     * Name of the reason.
     *
     * @var string
     */
    protected $name;
    /**
     * Text of the reason.
     *
     * @var string
     */
    protected $text;

    /**
     * Job ID.
     */
    public function getJobId(): int
    {
        return $this->jobId;
    }

    /**
     * Job ID.
     */
    public function setJobId(int $jobId): self
    {
        $this->jobId = $jobId;

        return $this;
    }

    /**
     * ID of the reason.
     */
    public function getReasonId(): int
    {
        return $this->reasonId;
    }

    /**
     * ID of the reason.
     */
    public function setReasonId(int $reasonId): self
    {
        $this->reasonId = $reasonId;

        return $this;
    }

    /**
     * Name of the reason.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Name of the reason.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Text of the reason.
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Text of the reason.
     */
    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }
}
