<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace CompWright\ServiceTitan\Model;

class InventoryV2PurchaseOrderResponse
{
    /**
     * Purchase order Id.
     *
     * @var int
     */
    protected $id;
    /**
     * Purchase order number.
     *
     * @var string
     */
    protected $number;
    /**
     * Id of invoice associated with PO.
     *
     * @var int|null
     */
    protected $invoiceId;
    /**
     * Id of job associated with PO.
     *
     * @var int|null
     */
    protected $jobId;
    /**
     * Id of project associated with PO.
     *
     * @var int|null
     */
    protected $projectId;
    /**
     * Status of this PO.
     *
     * @var string
     */
    protected $status;
    /**
     * The purchase order type Id of this PO.
     *
     * @var int
     */
    protected $typeId;
    /**
     * Id of vendor for this PO.
     *
     * @var int
     */
    protected $vendorId;
    /**
     * Id of technician for this PO.
     *
     * @var int|null
     */
    protected $technicianId;
    /**
     * Shipping address for this PO.
     *
     * @var mixed
     */
    protected $shipTo;
    /**
     * Id of business unit for this PO.
     *
     * @var int|null
     */
    protected $businessUnitId;
    /**
     * Inventory location Id of PO.
     *
     * @var int|null
     */
    protected $inventoryLocationId;
    /**
     * Batch Id of PO.
     *
     * @var int|null
     */
    protected $batchId;
    /**
     * Vendor document number of PO.
     *
     * @var string
     */
    protected $vendorDocumentNumber;
    /**
     * PO date.
     *
     * @var \DateTime
     */
    protected $date;
    /**
     * PO required on date.
     *
     * @var \DateTime|null
     */
    protected $requiredOn;
    /**
     * PO sent on date.
     *
     * @var \DateTime|null
     */
    protected $sentOn;
    /**
     * PO received on date.
     *
     * @var \DateTime|null
     */
    protected $receivedOn;
    /**
     * When PO was created, system date.
     *
     * @var \DateTime
     */
    protected $createdOn;
    /**
     * When PO was last modified, system date.
     *
     * @var \DateTime
     */
    protected $modifiedOn;
    /**
     * PO total, including items cost, tax and shipping cost.
     *
     * @var float
     */
    protected $total;
    /**
     * PO tax.
     *
     * @var float
     */
    protected $tax;
    /**
     * PO shipping cost.
     *
     * @var float
     */
    protected $shipping;
    /**
     * PO summary/memo.
     *
     * @var string
     */
    protected $summary;
    /**
     * List of PO items.
     *
     * @var InventoryV2PurchaseOrderItemResponse[]
     */
    protected $items;
    /**
     * List of custom fields for this PO.
     *
     * @var InventoryV2CustomFieldResponse[]
     */
    protected $customFields;

    /**
     * Purchase order Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Purchase order Id.
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Purchase order number.
     */
    public function getNumber(): string
    {
        return $this->number;
    }

    /**
     * Purchase order number.
     */
    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Id of invoice associated with PO.
     */
    public function getInvoiceId(): ?int
    {
        return $this->invoiceId;
    }

    /**
     * Id of invoice associated with PO.
     */
    public function setInvoiceId(?int $invoiceId): self
    {
        $this->invoiceId = $invoiceId;

        return $this;
    }

    /**
     * Id of job associated with PO.
     */
    public function getJobId(): ?int
    {
        return $this->jobId;
    }

    /**
     * Id of job associated with PO.
     */
    public function setJobId(?int $jobId): self
    {
        $this->jobId = $jobId;

        return $this;
    }

    /**
     * Id of project associated with PO.
     */
    public function getProjectId(): ?int
    {
        return $this->projectId;
    }

    /**
     * Id of project associated with PO.
     */
    public function setProjectId(?int $projectId): self
    {
        $this->projectId = $projectId;

        return $this;
    }

    /**
     * Status of this PO.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Status of this PO.
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * The purchase order type Id of this PO.
     */
    public function getTypeId(): int
    {
        return $this->typeId;
    }

    /**
     * The purchase order type Id of this PO.
     */
    public function setTypeId(int $typeId): self
    {
        $this->typeId = $typeId;

        return $this;
    }

    /**
     * Id of vendor for this PO.
     */
    public function getVendorId(): int
    {
        return $this->vendorId;
    }

    /**
     * Id of vendor for this PO.
     */
    public function setVendorId(int $vendorId): self
    {
        $this->vendorId = $vendorId;

        return $this;
    }

    /**
     * Id of technician for this PO.
     */
    public function getTechnicianId(): ?int
    {
        return $this->technicianId;
    }

    /**
     * Id of technician for this PO.
     */
    public function setTechnicianId(?int $technicianId): self
    {
        $this->technicianId = $technicianId;

        return $this;
    }

    /**
     * Shipping address for this PO.
     *
     * @return mixed
     */
    public function getShipTo()
    {
        return $this->shipTo;
    }

    /**
     * Shipping address for this PO.
     *
     * @param mixed $shipTo
     */
    public function setShipTo($shipTo): self
    {
        $this->shipTo = $shipTo;

        return $this;
    }

    /**
     * Id of business unit for this PO.
     */
    public function getBusinessUnitId(): ?int
    {
        return $this->businessUnitId;
    }

    /**
     * Id of business unit for this PO.
     */
    public function setBusinessUnitId(?int $businessUnitId): self
    {
        $this->businessUnitId = $businessUnitId;

        return $this;
    }

    /**
     * Inventory location Id of PO.
     */
    public function getInventoryLocationId(): ?int
    {
        return $this->inventoryLocationId;
    }

    /**
     * Inventory location Id of PO.
     */
    public function setInventoryLocationId(?int $inventoryLocationId): self
    {
        $this->inventoryLocationId = $inventoryLocationId;

        return $this;
    }

    /**
     * Batch Id of PO.
     */
    public function getBatchId(): ?int
    {
        return $this->batchId;
    }

    /**
     * Batch Id of PO.
     */
    public function setBatchId(?int $batchId): self
    {
        $this->batchId = $batchId;

        return $this;
    }

    /**
     * Vendor document number of PO.
     */
    public function getVendorDocumentNumber(): string
    {
        return $this->vendorDocumentNumber;
    }

    /**
     * Vendor document number of PO.
     */
    public function setVendorDocumentNumber(string $vendorDocumentNumber): self
    {
        $this->vendorDocumentNumber = $vendorDocumentNumber;

        return $this;
    }

    /**
     * PO date.
     */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * PO date.
     */
    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * PO required on date.
     */
    public function getRequiredOn(): ?\DateTime
    {
        return $this->requiredOn;
    }

    /**
     * PO required on date.
     */
    public function setRequiredOn(?\DateTime $requiredOn): self
    {
        $this->requiredOn = $requiredOn;

        return $this;
    }

    /**
     * PO sent on date.
     */
    public function getSentOn(): ?\DateTime
    {
        return $this->sentOn;
    }

    /**
     * PO sent on date.
     */
    public function setSentOn(?\DateTime $sentOn): self
    {
        $this->sentOn = $sentOn;

        return $this;
    }

    /**
     * PO received on date.
     */
    public function getReceivedOn(): ?\DateTime
    {
        return $this->receivedOn;
    }

    /**
     * PO received on date.
     */
    public function setReceivedOn(?\DateTime $receivedOn): self
    {
        $this->receivedOn = $receivedOn;

        return $this;
    }

    /**
     * When PO was created, system date.
     */
    public function getCreatedOn(): \DateTime
    {
        return $this->createdOn;
    }

    /**
     * When PO was created, system date.
     */
    public function setCreatedOn(\DateTime $createdOn): self
    {
        $this->createdOn = $createdOn;

        return $this;
    }

    /**
     * When PO was last modified, system date.
     */
    public function getModifiedOn(): \DateTime
    {
        return $this->modifiedOn;
    }

    /**
     * When PO was last modified, system date.
     */
    public function setModifiedOn(\DateTime $modifiedOn): self
    {
        $this->modifiedOn = $modifiedOn;

        return $this;
    }

    /**
     * PO total, including items cost, tax and shipping cost.
     */
    public function getTotal(): float
    {
        return $this->total;
    }

    /**
     * PO total, including items cost, tax and shipping cost.
     */
    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    /**
     * PO tax.
     */
    public function getTax(): float
    {
        return $this->tax;
    }

    /**
     * PO tax.
     */
    public function setTax(float $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

    /**
     * PO shipping cost.
     */
    public function getShipping(): float
    {
        return $this->shipping;
    }

    /**
     * PO shipping cost.
     */
    public function setShipping(float $shipping): self
    {
        $this->shipping = $shipping;

        return $this;
    }

    /**
     * PO summary/memo.
     */
    public function getSummary(): string
    {
        return $this->summary;
    }

    /**
     * PO summary/memo.
     */
    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    /**
     * List of PO items.
     *
     * @return InventoryV2PurchaseOrderItemResponse[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * List of PO items.
     *
     * @param InventoryV2PurchaseOrderItemResponse[] $items
     */
    public function setItems(array $items): self
    {
        $this->items = $items;

        return $this;
    }

    /**
     * List of custom fields for this PO.
     *
     * @return InventoryV2CustomFieldResponse[]
     */
    public function getCustomFields(): array
    {
        return $this->customFields;
    }

    /**
     * List of custom fields for this PO.
     *
     * @param InventoryV2CustomFieldResponse[] $customFields
     */
    public function setCustomFields(array $customFields): self
    {
        $this->customFields = $customFields;

        return $this;
    }
}
