<?php
/**
 * AccountingV2TaxBaseTypeNames
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CompWright\ServiceTitan\Model;
use \CompWright\ServiceTitan\ObjectSerializer;

/**
 * AccountingV2TaxBaseTypeNames Class Doc Comment
 *
 * @category Class
 * @description Indicates the types of tax applied for a given rate
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountingV2TaxBaseTypeNames
{
    /**
     * Possible values of this enum
     */
    public const SUBTOTAL = 'Subtotal';

    public const LABOR = 'Labor';

    public const MATERIAL = 'Material';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SUBTOTAL,
            self::LABOR,
            self::MATERIAL
        ];
    }
}


