<?php
/**
 * MembershipsV2LocationRecurringServiceResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Memberships
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CompWright\ServiceTitan\Model;

use \ArrayAccess;
use \CompWright\ServiceTitan\ObjectSerializer;

/**
 * MembershipsV2LocationRecurringServiceResponse Class Doc Comment
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MembershipsV2LocationRecurringServiceResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Memberships.V2.LocationRecurringServiceResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'active' => 'bool',
        'created_on' => '\DateTime',
        'created_by_id' => 'int',
        'modified_on' => '\DateTime',
        'import_id' => 'string',
        'membership_id' => 'int',
        'location_id' => 'int',
        'recurring_service_type_id' => 'int',
        'duration_type' => '\CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseDurationType',
        'duration_length' => 'int',
        'from' => '\DateTime',
        'to' => '\DateTime',
        'memo' => 'string',
        'invoice_template_id' => 'int',
        'invoice_template_for_following_years_id' => 'int',
        'first_visit_complete' => 'bool',
        'activated_from_id' => 'int',
        'allocation' => 'float',
        'business_unit_id' => 'int',
        'job_type_id' => 'int',
        'campaign_id' => 'int',
        'priority' => '\CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponsePriority',
        'job_summary' => 'string',
        'recurrence_type' => '\CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceType',
        'recurrence_interval' => 'int',
        'recurrence_months' => '\CompWright\ServiceTitan\Model\MembershipsV2Month[]',
        'recurrence_days_of_week' => '\CompWright\ServiceTitan\Model\MembershipsV2WeekDay[]',
        'recurrence_week' => '\CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceWeek',
        'recurrence_day_of_nth_week' => '\CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceDayOfNthWeek',
        'recurrence_days_of_month' => 'int[]',
        'job_start_time' => 'string',
        'estimated_payroll_cost' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'active' => null,
        'created_on' => 'date-time',
        'created_by_id' => 'int64',
        'modified_on' => 'date-time',
        'import_id' => null,
        'membership_id' => 'int64',
        'location_id' => 'int64',
        'recurring_service_type_id' => 'int64',
        'duration_type' => null,
        'duration_length' => 'int32',
        'from' => 'date-time',
        'to' => 'date-time',
        'memo' => null,
        'invoice_template_id' => 'int64',
        'invoice_template_for_following_years_id' => 'int64',
        'first_visit_complete' => null,
        'activated_from_id' => 'int64',
        'allocation' => 'decimal',
        'business_unit_id' => 'int64',
        'job_type_id' => 'int64',
        'campaign_id' => 'int64',
        'priority' => null,
        'job_summary' => null,
        'recurrence_type' => null,
        'recurrence_interval' => 'int32',
        'recurrence_months' => null,
        'recurrence_days_of_week' => null,
        'recurrence_week' => null,
        'recurrence_day_of_nth_week' => null,
        'recurrence_days_of_month' => 'int32',
        'job_start_time' => 'time-span',
        'estimated_payroll_cost' => 'decimal'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'active' => false,
        'created_on' => false,
        'created_by_id' => true,
        'modified_on' => false,
        'import_id' => true,
        'membership_id' => true,
        'location_id' => false,
        'recurring_service_type_id' => false,
        'duration_type' => false,
        'duration_length' => false,
        'from' => true,
        'to' => true,
        'memo' => true,
        'invoice_template_id' => true,
        'invoice_template_for_following_years_id' => true,
        'first_visit_complete' => false,
        'activated_from_id' => true,
        'allocation' => false,
        'business_unit_id' => true,
        'job_type_id' => true,
        'campaign_id' => true,
        'priority' => false,
        'job_summary' => true,
        'recurrence_type' => false,
        'recurrence_interval' => false,
        'recurrence_months' => false,
        'recurrence_days_of_week' => false,
        'recurrence_week' => false,
        'recurrence_day_of_nth_week' => true,
        'recurrence_days_of_month' => false,
        'job_start_time' => true,
        'estimated_payroll_cost' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'active' => 'active',
        'created_on' => 'createdOn',
        'created_by_id' => 'createdById',
        'modified_on' => 'modifiedOn',
        'import_id' => 'importId',
        'membership_id' => 'membershipId',
        'location_id' => 'locationId',
        'recurring_service_type_id' => 'recurringServiceTypeId',
        'duration_type' => 'durationType',
        'duration_length' => 'durationLength',
        'from' => 'from',
        'to' => 'to',
        'memo' => 'memo',
        'invoice_template_id' => 'invoiceTemplateId',
        'invoice_template_for_following_years_id' => 'invoiceTemplateForFollowingYearsId',
        'first_visit_complete' => 'firstVisitComplete',
        'activated_from_id' => 'activatedFromId',
        'allocation' => 'allocation',
        'business_unit_id' => 'businessUnitId',
        'job_type_id' => 'jobTypeId',
        'campaign_id' => 'campaignId',
        'priority' => 'priority',
        'job_summary' => 'jobSummary',
        'recurrence_type' => 'recurrenceType',
        'recurrence_interval' => 'recurrenceInterval',
        'recurrence_months' => 'recurrenceMonths',
        'recurrence_days_of_week' => 'recurrenceDaysOfWeek',
        'recurrence_week' => 'recurrenceWeek',
        'recurrence_day_of_nth_week' => 'recurrenceDayOfNthWeek',
        'recurrence_days_of_month' => 'recurrenceDaysOfMonth',
        'job_start_time' => 'jobStartTime',
        'estimated_payroll_cost' => 'estimatedPayrollCost'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'active' => 'setActive',
        'created_on' => 'setCreatedOn',
        'created_by_id' => 'setCreatedById',
        'modified_on' => 'setModifiedOn',
        'import_id' => 'setImportId',
        'membership_id' => 'setMembershipId',
        'location_id' => 'setLocationId',
        'recurring_service_type_id' => 'setRecurringServiceTypeId',
        'duration_type' => 'setDurationType',
        'duration_length' => 'setDurationLength',
        'from' => 'setFrom',
        'to' => 'setTo',
        'memo' => 'setMemo',
        'invoice_template_id' => 'setInvoiceTemplateId',
        'invoice_template_for_following_years_id' => 'setInvoiceTemplateForFollowingYearsId',
        'first_visit_complete' => 'setFirstVisitComplete',
        'activated_from_id' => 'setActivatedFromId',
        'allocation' => 'setAllocation',
        'business_unit_id' => 'setBusinessUnitId',
        'job_type_id' => 'setJobTypeId',
        'campaign_id' => 'setCampaignId',
        'priority' => 'setPriority',
        'job_summary' => 'setJobSummary',
        'recurrence_type' => 'setRecurrenceType',
        'recurrence_interval' => 'setRecurrenceInterval',
        'recurrence_months' => 'setRecurrenceMonths',
        'recurrence_days_of_week' => 'setRecurrenceDaysOfWeek',
        'recurrence_week' => 'setRecurrenceWeek',
        'recurrence_day_of_nth_week' => 'setRecurrenceDayOfNthWeek',
        'recurrence_days_of_month' => 'setRecurrenceDaysOfMonth',
        'job_start_time' => 'setJobStartTime',
        'estimated_payroll_cost' => 'setEstimatedPayrollCost'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'active' => 'getActive',
        'created_on' => 'getCreatedOn',
        'created_by_id' => 'getCreatedById',
        'modified_on' => 'getModifiedOn',
        'import_id' => 'getImportId',
        'membership_id' => 'getMembershipId',
        'location_id' => 'getLocationId',
        'recurring_service_type_id' => 'getRecurringServiceTypeId',
        'duration_type' => 'getDurationType',
        'duration_length' => 'getDurationLength',
        'from' => 'getFrom',
        'to' => 'getTo',
        'memo' => 'getMemo',
        'invoice_template_id' => 'getInvoiceTemplateId',
        'invoice_template_for_following_years_id' => 'getInvoiceTemplateForFollowingYearsId',
        'first_visit_complete' => 'getFirstVisitComplete',
        'activated_from_id' => 'getActivatedFromId',
        'allocation' => 'getAllocation',
        'business_unit_id' => 'getBusinessUnitId',
        'job_type_id' => 'getJobTypeId',
        'campaign_id' => 'getCampaignId',
        'priority' => 'getPriority',
        'job_summary' => 'getJobSummary',
        'recurrence_type' => 'getRecurrenceType',
        'recurrence_interval' => 'getRecurrenceInterval',
        'recurrence_months' => 'getRecurrenceMonths',
        'recurrence_days_of_week' => 'getRecurrenceDaysOfWeek',
        'recurrence_week' => 'getRecurrenceWeek',
        'recurrence_day_of_nth_week' => 'getRecurrenceDayOfNthWeek',
        'recurrence_days_of_month' => 'getRecurrenceDaysOfMonth',
        'job_start_time' => 'getJobStartTime',
        'estimated_payroll_cost' => 'getEstimatedPayrollCost'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('created_on', $data ?? [], null);
        $this->setIfExists('created_by_id', $data ?? [], null);
        $this->setIfExists('modified_on', $data ?? [], null);
        $this->setIfExists('import_id', $data ?? [], null);
        $this->setIfExists('membership_id', $data ?? [], null);
        $this->setIfExists('location_id', $data ?? [], null);
        $this->setIfExists('recurring_service_type_id', $data ?? [], null);
        $this->setIfExists('duration_type', $data ?? [], null);
        $this->setIfExists('duration_length', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('memo', $data ?? [], null);
        $this->setIfExists('invoice_template_id', $data ?? [], null);
        $this->setIfExists('invoice_template_for_following_years_id', $data ?? [], null);
        $this->setIfExists('first_visit_complete', $data ?? [], null);
        $this->setIfExists('activated_from_id', $data ?? [], null);
        $this->setIfExists('allocation', $data ?? [], null);
        $this->setIfExists('business_unit_id', $data ?? [], null);
        $this->setIfExists('job_type_id', $data ?? [], null);
        $this->setIfExists('campaign_id', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('job_summary', $data ?? [], null);
        $this->setIfExists('recurrence_type', $data ?? [], null);
        $this->setIfExists('recurrence_interval', $data ?? [], null);
        $this->setIfExists('recurrence_months', $data ?? [], null);
        $this->setIfExists('recurrence_days_of_week', $data ?? [], null);
        $this->setIfExists('recurrence_week', $data ?? [], null);
        $this->setIfExists('recurrence_day_of_nth_week', $data ?? [], null);
        $this->setIfExists('recurrence_days_of_month', $data ?? [], null);
        $this->setIfExists('job_start_time', $data ?? [], null);
        $this->setIfExists('estimated_payroll_cost', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['active'] === null) {
            $invalidProperties[] = "'active' can't be null";
        }
        if ($this->container['created_on'] === null) {
            $invalidProperties[] = "'created_on' can't be null";
        }
        if ($this->container['modified_on'] === null) {
            $invalidProperties[] = "'modified_on' can't be null";
        }
        if ($this->container['location_id'] === null) {
            $invalidProperties[] = "'location_id' can't be null";
        }
        if ($this->container['recurring_service_type_id'] === null) {
            $invalidProperties[] = "'recurring_service_type_id' can't be null";
        }
        if ($this->container['duration_type'] === null) {
            $invalidProperties[] = "'duration_type' can't be null";
        }
        if ($this->container['duration_length'] === null) {
            $invalidProperties[] = "'duration_length' can't be null";
        }
        if ($this->container['first_visit_complete'] === null) {
            $invalidProperties[] = "'first_visit_complete' can't be null";
        }
        if ($this->container['allocation'] === null) {
            $invalidProperties[] = "'allocation' can't be null";
        }
        if ($this->container['priority'] === null) {
            $invalidProperties[] = "'priority' can't be null";
        }
        if ($this->container['recurrence_type'] === null) {
            $invalidProperties[] = "'recurrence_type' can't be null";
        }
        if ($this->container['recurrence_interval'] === null) {
            $invalidProperties[] = "'recurrence_interval' can't be null";
        }
        if ($this->container['recurrence_months'] === null) {
            $invalidProperties[] = "'recurrence_months' can't be null";
        }
        if ($this->container['recurrence_days_of_week'] === null) {
            $invalidProperties[] = "'recurrence_days_of_week' can't be null";
        }
        if ($this->container['recurrence_week'] === null) {
            $invalidProperties[] = "'recurrence_week' can't be null";
        }
        if ($this->container['recurrence_days_of_month'] === null) {
            $invalidProperties[] = "'recurrence_days_of_month' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Recurring service ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Recurring service name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active Whether recurring service is active
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets created_on
     *
     * @return \DateTime
     */
    public function getCreatedOn()
    {
        return $this->container['created_on'];
    }

    /**
     * Sets created_on
     *
     * @param \DateTime $created_on When recurring service was created
     *
     * @return self
     */
    public function setCreatedOn($created_on)
    {
        if (is_null($created_on)) {
            throw new \InvalidArgumentException('non-nullable created_on cannot be null');
        }
        $this->container['created_on'] = $created_on;

        return $this;
    }

    /**
     * Gets created_by_id
     *
     * @return int|null
     */
    public function getCreatedById()
    {
        return $this->container['created_by_id'];
    }

    /**
     * Sets created_by_id
     *
     * @param int|null $created_by_id ID of the user that created this recurring service
     *
     * @return self
     */
    public function setCreatedById($created_by_id)
    {
        if (is_null($created_by_id)) {
            array_push($this->openAPINullablesSetToNull, 'created_by_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_by_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_by_id'] = $created_by_id;

        return $this;
    }

    /**
     * Gets modified_on
     *
     * @return \DateTime
     */
    public function getModifiedOn()
    {
        return $this->container['modified_on'];
    }

    /**
     * Sets modified_on
     *
     * @param \DateTime $modified_on When recurring service was modified
     *
     * @return self
     */
    public function setModifiedOn($modified_on)
    {
        if (is_null($modified_on)) {
            throw new \InvalidArgumentException('non-nullable modified_on cannot be null');
        }
        $this->container['modified_on'] = $modified_on;

        return $this;
    }

    /**
     * Gets import_id
     *
     * @return string|null
     */
    public function getImportId()
    {
        return $this->container['import_id'];
    }

    /**
     * Sets import_id
     *
     * @param string|null $import_id Internal import ID label
     *
     * @return self
     */
    public function setImportId($import_id)
    {
        if (is_null($import_id)) {
            array_push($this->openAPINullablesSetToNull, 'import_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('import_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['import_id'] = $import_id;

        return $this;
    }

    /**
     * Gets membership_id
     *
     * @return int|null
     */
    public function getMembershipId()
    {
        return $this->container['membership_id'];
    }

    /**
     * Sets membership_id
     *
     * @param int|null $membership_id Customer membership ID
     *
     * @return self
     */
    public function setMembershipId($membership_id)
    {
        if (is_null($membership_id)) {
            array_push($this->openAPINullablesSetToNull, 'membership_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('membership_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['membership_id'] = $membership_id;

        return $this;
    }

    /**
     * Gets location_id
     *
     * @return int
     */
    public function getLocationId()
    {
        return $this->container['location_id'];
    }

    /**
     * Sets location_id
     *
     * @param int $location_id Location ID
     *
     * @return self
     */
    public function setLocationId($location_id)
    {
        if (is_null($location_id)) {
            throw new \InvalidArgumentException('non-nullable location_id cannot be null');
        }
        $this->container['location_id'] = $location_id;

        return $this;
    }

    /**
     * Gets recurring_service_type_id
     *
     * @return int
     */
    public function getRecurringServiceTypeId()
    {
        return $this->container['recurring_service_type_id'];
    }

    /**
     * Sets recurring_service_type_id
     *
     * @param int $recurring_service_type_id Recurring Service Type ID
     *
     * @return self
     */
    public function setRecurringServiceTypeId($recurring_service_type_id)
    {
        if (is_null($recurring_service_type_id)) {
            throw new \InvalidArgumentException('non-nullable recurring_service_type_id cannot be null');
        }
        $this->container['recurring_service_type_id'] = $recurring_service_type_id;

        return $this;
    }

    /**
     * Gets duration_type
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseDurationType
     */
    public function getDurationType()
    {
        return $this->container['duration_type'];
    }

    /**
     * Sets duration_type
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseDurationType $duration_type duration_type
     *
     * @return self
     */
    public function setDurationType($duration_type)
    {
        if (is_null($duration_type)) {
            throw new \InvalidArgumentException('non-nullable duration_type cannot be null');
        }
        $this->container['duration_type'] = $duration_type;

        return $this;
    }

    /**
     * Gets duration_length
     *
     * @return int
     */
    public function getDurationLength()
    {
        return $this->container['duration_length'];
    }

    /**
     * Sets duration_length
     *
     * @param int $duration_length The duration length for the given duration type
     *
     * @return self
     */
    public function setDurationLength($duration_length)
    {
        if (is_null($duration_length)) {
            throw new \InvalidArgumentException('non-nullable duration_length cannot be null');
        }
        $this->container['duration_length'] = $duration_length;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \DateTime|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \DateTime|null $from Beginning date of recurring service
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            array_push($this->openAPINullablesSetToNull, 'from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \DateTime|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \DateTime|null $to End date of recurring service
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            array_push($this->openAPINullablesSetToNull, 'to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string|null
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string|null $memo Memo
     *
     * @return self
     */
    public function setMemo($memo)
    {
        if (is_null($memo)) {
            array_push($this->openAPINullablesSetToNull, 'memo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('memo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets invoice_template_id
     *
     * @return int|null
     */
    public function getInvoiceTemplateId()
    {
        return $this->container['invoice_template_id'];
    }

    /**
     * Sets invoice_template_id
     *
     * @param int|null $invoice_template_id Invoice template ID
     *
     * @return self
     */
    public function setInvoiceTemplateId($invoice_template_id)
    {
        if (is_null($invoice_template_id)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_template_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_template_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_template_id'] = $invoice_template_id;

        return $this;
    }

    /**
     * Gets invoice_template_for_following_years_id
     *
     * @return int|null
     */
    public function getInvoiceTemplateForFollowingYearsId()
    {
        return $this->container['invoice_template_for_following_years_id'];
    }

    /**
     * Sets invoice_template_for_following_years_id
     *
     * @param int|null $invoice_template_for_following_years_id Invoice template ID for the 2nd year and following (for ongoing memberships)
     *
     * @return self
     */
    public function setInvoiceTemplateForFollowingYearsId($invoice_template_for_following_years_id)
    {
        if (is_null($invoice_template_for_following_years_id)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_template_for_following_years_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_template_for_following_years_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_template_for_following_years_id'] = $invoice_template_for_following_years_id;

        return $this;
    }

    /**
     * Gets first_visit_complete
     *
     * @return bool
     */
    public function getFirstVisitComplete()
    {
        return $this->container['first_visit_complete'];
    }

    /**
     * Sets first_visit_complete
     *
     * @param bool $first_visit_complete Whether first visit is complete
     *
     * @return self
     */
    public function setFirstVisitComplete($first_visit_complete)
    {
        if (is_null($first_visit_complete)) {
            throw new \InvalidArgumentException('non-nullable first_visit_complete cannot be null');
        }
        $this->container['first_visit_complete'] = $first_visit_complete;

        return $this;
    }

    /**
     * Gets activated_from_id
     *
     * @return int|null
     */
    public function getActivatedFromId()
    {
        return $this->container['activated_from_id'];
    }

    /**
     * Sets activated_from_id
     *
     * @param int|null $activated_from_id ID of the invoice item that is the sale task of this membership
     *
     * @return self
     */
    public function setActivatedFromId($activated_from_id)
    {
        if (is_null($activated_from_id)) {
            array_push($this->openAPINullablesSetToNull, 'activated_from_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('activated_from_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['activated_from_id'] = $activated_from_id;

        return $this;
    }

    /**
     * Gets allocation
     *
     * @return float
     */
    public function getAllocation()
    {
        return $this->container['allocation'];
    }

    /**
     * Sets allocation
     *
     * @param float $allocation Recurring service allocation
     *
     * @return self
     */
    public function setAllocation($allocation)
    {
        if (is_null($allocation)) {
            throw new \InvalidArgumentException('non-nullable allocation cannot be null');
        }
        $this->container['allocation'] = $allocation;

        return $this;
    }

    /**
     * Gets business_unit_id
     *
     * @return int|null
     */
    public function getBusinessUnitId()
    {
        return $this->container['business_unit_id'];
    }

    /**
     * Sets business_unit_id
     *
     * @param int|null $business_unit_id Business unit ID
     *
     * @return self
     */
    public function setBusinessUnitId($business_unit_id)
    {
        if (is_null($business_unit_id)) {
            array_push($this->openAPINullablesSetToNull, 'business_unit_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('business_unit_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['business_unit_id'] = $business_unit_id;

        return $this;
    }

    /**
     * Gets job_type_id
     *
     * @return int|null
     */
    public function getJobTypeId()
    {
        return $this->container['job_type_id'];
    }

    /**
     * Sets job_type_id
     *
     * @param int|null $job_type_id Job type ID
     *
     * @return self
     */
    public function setJobTypeId($job_type_id)
    {
        if (is_null($job_type_id)) {
            array_push($this->openAPINullablesSetToNull, 'job_type_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('job_type_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['job_type_id'] = $job_type_id;

        return $this;
    }

    /**
     * Gets campaign_id
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param int|null $campaign_id Campaign ID
     *
     * @return self
     */
    public function setCampaignId($campaign_id)
    {
        if (is_null($campaign_id)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponsePriority
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponsePriority $priority priority
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            throw new \InvalidArgumentException('non-nullable priority cannot be null');
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets job_summary
     *
     * @return string|null
     */
    public function getJobSummary()
    {
        return $this->container['job_summary'];
    }

    /**
     * Sets job_summary
     *
     * @param string|null $job_summary Job summary
     *
     * @return self
     */
    public function setJobSummary($job_summary)
    {
        if (is_null($job_summary)) {
            array_push($this->openAPINullablesSetToNull, 'job_summary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('job_summary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['job_summary'] = $job_summary;

        return $this;
    }

    /**
     * Gets recurrence_type
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceType
     */
    public function getRecurrenceType()
    {
        return $this->container['recurrence_type'];
    }

    /**
     * Sets recurrence_type
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceType $recurrence_type recurrence_type
     *
     * @return self
     */
    public function setRecurrenceType($recurrence_type)
    {
        if (is_null($recurrence_type)) {
            throw new \InvalidArgumentException('non-nullable recurrence_type cannot be null');
        }
        $this->container['recurrence_type'] = $recurrence_type;

        return $this;
    }

    /**
     * Gets recurrence_interval
     *
     * @return int
     */
    public function getRecurrenceInterval()
    {
        return $this->container['recurrence_interval'];
    }

    /**
     * Sets recurrence_interval
     *
     * @param int $recurrence_interval The recurrence interval for the given recurrence type. Can be 0 when RecurrenceType is Seasonal.
     *
     * @return self
     */
    public function setRecurrenceInterval($recurrence_interval)
    {
        if (is_null($recurrence_interval)) {
            throw new \InvalidArgumentException('non-nullable recurrence_interval cannot be null');
        }
        $this->container['recurrence_interval'] = $recurrence_interval;

        return $this;
    }

    /**
     * Gets recurrence_months
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2Month[]
     */
    public function getRecurrenceMonths()
    {
        return $this->container['recurrence_months'];
    }

    /**
     * Sets recurrence_months
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2Month[] $recurrence_months A list of months when the recurring service occurs, if it is a seasonal recurrence type
     *
     * @return self
     */
    public function setRecurrenceMonths($recurrence_months)
    {
        if (is_null($recurrence_months)) {
            throw new \InvalidArgumentException('non-nullable recurrence_months cannot be null');
        }
        $this->container['recurrence_months'] = $recurrence_months;

        return $this;
    }

    /**
     * Gets recurrence_days_of_week
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2WeekDay[]
     */
    public function getRecurrenceDaysOfWeek()
    {
        return $this->container['recurrence_days_of_week'];
    }

    /**
     * Sets recurrence_days_of_week
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2WeekDay[] $recurrence_days_of_week A list specifying which days of the week this recurring service recurs when RecurrenceType is Weekly
     *
     * @return self
     */
    public function setRecurrenceDaysOfWeek($recurrence_days_of_week)
    {
        if (is_null($recurrence_days_of_week)) {
            throw new \InvalidArgumentException('non-nullable recurrence_days_of_week cannot be null');
        }
        $this->container['recurrence_days_of_week'] = $recurrence_days_of_week;

        return $this;
    }

    /**
     * Gets recurrence_week
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceWeek
     */
    public function getRecurrenceWeek()
    {
        return $this->container['recurrence_week'];
    }

    /**
     * Sets recurrence_week
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceWeek $recurrence_week recurrence_week
     *
     * @return self
     */
    public function setRecurrenceWeek($recurrence_week)
    {
        if (is_null($recurrence_week)) {
            throw new \InvalidArgumentException('non-nullable recurrence_week cannot be null');
        }
        $this->container['recurrence_week'] = $recurrence_week;

        return $this;
    }

    /**
     * Gets recurrence_day_of_nth_week
     *
     * @return \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceDayOfNthWeek|null
     */
    public function getRecurrenceDayOfNthWeek()
    {
        return $this->container['recurrence_day_of_nth_week'];
    }

    /**
     * Sets recurrence_day_of_nth_week
     *
     * @param \CompWright\ServiceTitan\Model\MembershipsV2LocationRecurringServiceResponseRecurrenceDayOfNthWeek|null $recurrence_day_of_nth_week recurrence_day_of_nth_week
     *
     * @return self
     */
    public function setRecurrenceDayOfNthWeek($recurrence_day_of_nth_week)
    {
        if (is_null($recurrence_day_of_nth_week)) {
            array_push($this->openAPINullablesSetToNull, 'recurrence_day_of_nth_week');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recurrence_day_of_nth_week', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recurrence_day_of_nth_week'] = $recurrence_day_of_nth_week;

        return $this;
    }

    /**
     * Gets recurrence_days_of_month
     *
     * @return int[]
     */
    public function getRecurrenceDaysOfMonth()
    {
        return $this->container['recurrence_days_of_month'];
    }

    /**
     * Sets recurrence_days_of_month
     *
     * @param int[] $recurrence_days_of_month A list of days of the month on which this recurring service recurs when RecurrenceType is Monthly.
     *
     * @return self
     */
    public function setRecurrenceDaysOfMonth($recurrence_days_of_month)
    {
        if (is_null($recurrence_days_of_month)) {
            throw new \InvalidArgumentException('non-nullable recurrence_days_of_month cannot be null');
        }
        $this->container['recurrence_days_of_month'] = $recurrence_days_of_month;

        return $this;
    }

    /**
     * Gets job_start_time
     *
     * @return string|null
     */
    public function getJobStartTime()
    {
        return $this->container['job_start_time'];
    }

    /**
     * Sets job_start_time
     *
     * @param string|null $job_start_time Job start time
     *
     * @return self
     */
    public function setJobStartTime($job_start_time)
    {
        if (is_null($job_start_time)) {
            array_push($this->openAPINullablesSetToNull, 'job_start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('job_start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['job_start_time'] = $job_start_time;

        return $this;
    }

    /**
     * Gets estimated_payroll_cost
     *
     * @return float|null
     */
    public function getEstimatedPayrollCost()
    {
        return $this->container['estimated_payroll_cost'];
    }

    /**
     * Sets estimated_payroll_cost
     *
     * @param float|null $estimated_payroll_cost Estimated payroll cost
     *
     * @return self
     */
    public function setEstimatedPayrollCost($estimated_payroll_cost)
    {
        if (is_null($estimated_payroll_cost)) {
            array_push($this->openAPINullablesSetToNull, 'estimated_payroll_cost');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estimated_payroll_cost', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estimated_payroll_cost'] = $estimated_payroll_cost;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


