openapi: 3.0.1
info:
  title: Forms
  version: '1.0'
servers:
  - url: https://api.servicetitan.io
paths:
  '/forms/v2/tenant/{tenant}/jobs/{id}/attachments':
    post:
      tags:
        - Jobs
      summary: Creates a Attachment on the specified Job
      description: Creates a Attachment on the specified Job
      operationId: Jobs_CreateAttachment
      parameters:
        - name: id
          in: path
          description: Format - int64. Job Id
          required: true
          schema:
            type: integer
            format: int64
        - name: tenant
          in: path
          description: Tenant ID
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            example:
              file: string
      responses:
        '200':
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forms.V2.AttachmentResponse'
              example:
                fileName: string
        '400':
          description: 'The request cannot be processed, check validation errors or request format'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
components:
  schemas:
    Forms.V2.AttachmentResponse:
      required:
        - fileName
      type: object
      properties:
        fileName:
          type: string
          description: Original filename
      additionalProperties: false
    ApiErrorResponse:
      required:
        - type
        - title
        - status
        - traceId
        - errors
        - data
      type: object
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type
        title:
          type: string
          description: 'A short, human-readable summary of the problem type'
        status:
          type: integer
          description: The HTTP status code generated by server
          format: int32
        traceId:
          type: string
          description: Internal trace ID for advanced diagnostics
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: 'Provides more details about errors occurred, which can potentially be used for visual display'
        data:
          type: object
          additionalProperties: { }
          description: 'Provides additional data, intended for programmatical usage'
      additionalProperties: false
      description: 'Detailed error response, following RFC 7807 recommendations (https://tools.ietf.org/html/rfc7807).'
  securitySchemes:
    appKey:
      type: apiKey
      name: ST-App-Key
      in: header
    bearerToken:
      type: http
      scheme: bearer
security:
  - appKey: [ ]
  - bearerToken: [ ]