<?php
/**
 * CustomerMembershipsApi
 * PHP version 7.3
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Memberships
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Jonathon Hill, CompWright Enterprises LLC (https://compwright.com)
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CompWright\ServiceTitan\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use CompWright\ServiceTitan\ApiException;
use CompWright\ServiceTitan\Configuration;
use CompWright\ServiceTitan\HeaderSelector;
use CompWright\ServiceTitan\ObjectSerializer;

/**
 * CustomerMembershipsApi Class Doc Comment
 *
 * @category Class
 * @package  CompWright\ServiceTitan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerMembershipsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation customerMembershipsCreate
     *
     * Creates membership sale invoice
     *
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateRequest $memberships_v2_membership_sale_invoice_create_request memberships_v2_membership_sale_invoice_create_request (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse
     */
    public function customerMembershipsCreate($tenant, $memberships_v2_membership_sale_invoice_create_request = null)
    {
        list($response) = $this->customerMembershipsCreateWithHttpInfo($tenant, $memberships_v2_membership_sale_invoice_create_request);
        return $response;
    }

    /**
     * Operation customerMembershipsCreateWithHttpInfo
     *
     * Creates membership sale invoice
     *
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateRequest $memberships_v2_membership_sale_invoice_create_request (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerMembershipsCreateWithHttpInfo($tenant, $memberships_v2_membership_sale_invoice_create_request = null)
    {
        $request = $this->customerMembershipsCreateRequest($tenant, $memberships_v2_membership_sale_invoice_create_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation customerMembershipsCreateAsync
     *
     * Creates membership sale invoice
     *
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateRequest $memberships_v2_membership_sale_invoice_create_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsCreateAsync($tenant, $memberships_v2_membership_sale_invoice_create_request = null)
    {
        return $this->customerMembershipsCreateAsyncWithHttpInfo($tenant, $memberships_v2_membership_sale_invoice_create_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerMembershipsCreateAsyncWithHttpInfo
     *
     * Creates membership sale invoice
     *
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateRequest $memberships_v2_membership_sale_invoice_create_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsCreateAsyncWithHttpInfo($tenant, $memberships_v2_membership_sale_invoice_create_request = null)
    {
        $returnType = '\CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateResponse';
        $request = $this->customerMembershipsCreateRequest($tenant, $memberships_v2_membership_sale_invoice_create_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerMembershipsCreate'
     *
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2MembershipSaleInvoiceCreateRequest $memberships_v2_membership_sale_invoice_create_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerMembershipsCreateRequest($tenant, $memberships_v2_membership_sale_invoice_create_request = null)
    {
        // verify the required parameter 'tenant' is set
        if ($tenant === null || (is_array($tenant) && count($tenant) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant when calling customerMembershipsCreate'
            );
        }

        $resourcePath = '/tenant/{tenant}/memberships/sale';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenant !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant' . '}',
                ObjectSerializer::toPathValue($tenant),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($memberships_v2_membership_sale_invoice_create_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($memberships_v2_membership_sale_invoice_create_request));
            } else {
                $httpBody = $memberships_v2_membership_sale_invoice_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('ST-App-Key');
        if ($apiKey !== null) {
            $headers['ST-App-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('servicetitanapplicationkey');
        if ($apiKey !== null) {
            $queryParams['servicetitanapplicationkey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerMembershipsGet
     *
     * Gets customer membership specified by ID
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse
     */
    public function customerMembershipsGet($id, $tenant)
    {
        list($response) = $this->customerMembershipsGetWithHttpInfo($id, $tenant);
        return $response;
    }

    /**
     * Operation customerMembershipsGetWithHttpInfo
     *
     * Gets customer membership specified by ID
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerMembershipsGetWithHttpInfo($id, $tenant)
    {
        $request = $this->customerMembershipsGetRequest($id, $tenant);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation customerMembershipsGetAsync
     *
     * Gets customer membership specified by ID
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsGetAsync($id, $tenant)
    {
        return $this->customerMembershipsGetAsyncWithHttpInfo($id, $tenant)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerMembershipsGetAsyncWithHttpInfo
     *
     * Gets customer membership specified by ID
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsGetAsyncWithHttpInfo($id, $tenant)
    {
        $returnType = '\CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipResponse';
        $request = $this->customerMembershipsGetRequest($id, $tenant);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerMembershipsGet'
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerMembershipsGetRequest($id, $tenant)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling customerMembershipsGet'
            );
        }
        // verify the required parameter 'tenant' is set
        if ($tenant === null || (is_array($tenant) && count($tenant) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant when calling customerMembershipsGet'
            );
        }

        $resourcePath = '/tenant/{tenant}/memberships/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($tenant !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant' . '}',
                ObjectSerializer::toPathValue($tenant),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('ST-App-Key');
        if ($apiKey !== null) {
            $headers['ST-App-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('servicetitanapplicationkey');
        if ($apiKey !== null) {
            $queryParams['servicetitanapplicationkey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerMembershipsGetList
     *
     * Gets a list of customer memberships
     *
     * @param  int $tenant Tenant ID (required)
     * @param  string $ids Perform lookup by multiple IDs (maximum 50) (optional)
     * @param  string $customer_ids Filters by customer IDs (optional)
     * @param  OneOfActiveQueryFilter $active What kind of items should be returned (only active items will be returned by default)\\ Values: [True, Any, False] (optional)
     * @param  OneOfMembershipsV2MembershipStatus $status Filters by membership status\\ Values: [Active, Suspended, Expired, Canceled, Deleted] (optional)
     * @param  int $duration Format - int32. Filters by membership duration (in months); use null for ongoing memberships (optional)
     * @param  OneOfMembershipsV2MembershipRecurrenceType $billing_frequency Filters by membership billing frequency\\ Values: [OneTime, Monthly, EveryOtherMonth, Quarterly, BiAnnual, Annual] (optional)
     * @param  \DateTime $created_before Format - date-time (as date-time in RFC3339). Return items created before certain date/time (in UTC) (optional)
     * @param  \DateTime $created_on_or_after Format - date-time (as date-time in RFC3339). Return items created on or after certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_before Format - date-time (as date-time in RFC3339). Return items modified before certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_on_or_after Format - date-time (as date-time in RFC3339). Return items modified on or after certain date/time (in UTC) (optional)
     * @param  int $page Format - int32. The logical number of page to return, starting from 1 (optional)
     * @param  int $page_size Format - int32. How many records to return (50 by default) (optional)
     * @param  bool $include_total Whether total count should be returned (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse
     */
    public function customerMembershipsGetList($tenant, $ids = null, $customer_ids = null, $active = null, $status = null, $duration = null, $billing_frequency = null, $created_before = null, $created_on_or_after = null, $modified_before = null, $modified_on_or_after = null, $page = null, $page_size = null, $include_total = null)
    {
        list($response) = $this->customerMembershipsGetListWithHttpInfo($tenant, $ids, $customer_ids, $active, $status, $duration, $billing_frequency, $created_before, $created_on_or_after, $modified_before, $modified_on_or_after, $page, $page_size, $include_total);
        return $response;
    }

    /**
     * Operation customerMembershipsGetListWithHttpInfo
     *
     * Gets a list of customer memberships
     *
     * @param  int $tenant Tenant ID (required)
     * @param  string $ids Perform lookup by multiple IDs (maximum 50) (optional)
     * @param  string $customer_ids Filters by customer IDs (optional)
     * @param  OneOfActiveQueryFilter $active What kind of items should be returned (only active items will be returned by default)\\ Values: [True, Any, False] (optional)
     * @param  OneOfMembershipsV2MembershipStatus $status Filters by membership status\\ Values: [Active, Suspended, Expired, Canceled, Deleted] (optional)
     * @param  int $duration Format - int32. Filters by membership duration (in months); use null for ongoing memberships (optional)
     * @param  OneOfMembershipsV2MembershipRecurrenceType $billing_frequency Filters by membership billing frequency\\ Values: [OneTime, Monthly, EveryOtherMonth, Quarterly, BiAnnual, Annual] (optional)
     * @param  \DateTime $created_before Format - date-time (as date-time in RFC3339). Return items created before certain date/time (in UTC) (optional)
     * @param  \DateTime $created_on_or_after Format - date-time (as date-time in RFC3339). Return items created on or after certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_before Format - date-time (as date-time in RFC3339). Return items modified before certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_on_or_after Format - date-time (as date-time in RFC3339). Return items modified on or after certain date/time (in UTC) (optional)
     * @param  int $page Format - int32. The logical number of page to return, starting from 1 (optional)
     * @param  int $page_size Format - int32. How many records to return (50 by default) (optional)
     * @param  bool $include_total Whether total count should be returned (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerMembershipsGetListWithHttpInfo($tenant, $ids = null, $customer_ids = null, $active = null, $status = null, $duration = null, $billing_frequency = null, $created_before = null, $created_on_or_after = null, $modified_before = null, $modified_on_or_after = null, $page = null, $page_size = null, $include_total = null)
    {
        $request = $this->customerMembershipsGetListRequest($tenant, $ids, $customer_ids, $active, $status, $duration, $billing_frequency, $created_before, $created_on_or_after, $modified_before, $modified_on_or_after, $page, $page_size, $include_total);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation customerMembershipsGetListAsync
     *
     * Gets a list of customer memberships
     *
     * @param  int $tenant Tenant ID (required)
     * @param  string $ids Perform lookup by multiple IDs (maximum 50) (optional)
     * @param  string $customer_ids Filters by customer IDs (optional)
     * @param  OneOfActiveQueryFilter $active What kind of items should be returned (only active items will be returned by default)\\ Values: [True, Any, False] (optional)
     * @param  OneOfMembershipsV2MembershipStatus $status Filters by membership status\\ Values: [Active, Suspended, Expired, Canceled, Deleted] (optional)
     * @param  int $duration Format - int32. Filters by membership duration (in months); use null for ongoing memberships (optional)
     * @param  OneOfMembershipsV2MembershipRecurrenceType $billing_frequency Filters by membership billing frequency\\ Values: [OneTime, Monthly, EveryOtherMonth, Quarterly, BiAnnual, Annual] (optional)
     * @param  \DateTime $created_before Format - date-time (as date-time in RFC3339). Return items created before certain date/time (in UTC) (optional)
     * @param  \DateTime $created_on_or_after Format - date-time (as date-time in RFC3339). Return items created on or after certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_before Format - date-time (as date-time in RFC3339). Return items modified before certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_on_or_after Format - date-time (as date-time in RFC3339). Return items modified on or after certain date/time (in UTC) (optional)
     * @param  int $page Format - int32. The logical number of page to return, starting from 1 (optional)
     * @param  int $page_size Format - int32. How many records to return (50 by default) (optional)
     * @param  bool $include_total Whether total count should be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsGetListAsync($tenant, $ids = null, $customer_ids = null, $active = null, $status = null, $duration = null, $billing_frequency = null, $created_before = null, $created_on_or_after = null, $modified_before = null, $modified_on_or_after = null, $page = null, $page_size = null, $include_total = null)
    {
        return $this->customerMembershipsGetListAsyncWithHttpInfo($tenant, $ids, $customer_ids, $active, $status, $duration, $billing_frequency, $created_before, $created_on_or_after, $modified_before, $modified_on_or_after, $page, $page_size, $include_total)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerMembershipsGetListAsyncWithHttpInfo
     *
     * Gets a list of customer memberships
     *
     * @param  int $tenant Tenant ID (required)
     * @param  string $ids Perform lookup by multiple IDs (maximum 50) (optional)
     * @param  string $customer_ids Filters by customer IDs (optional)
     * @param  OneOfActiveQueryFilter $active What kind of items should be returned (only active items will be returned by default)\\ Values: [True, Any, False] (optional)
     * @param  OneOfMembershipsV2MembershipStatus $status Filters by membership status\\ Values: [Active, Suspended, Expired, Canceled, Deleted] (optional)
     * @param  int $duration Format - int32. Filters by membership duration (in months); use null for ongoing memberships (optional)
     * @param  OneOfMembershipsV2MembershipRecurrenceType $billing_frequency Filters by membership billing frequency\\ Values: [OneTime, Monthly, EveryOtherMonth, Quarterly, BiAnnual, Annual] (optional)
     * @param  \DateTime $created_before Format - date-time (as date-time in RFC3339). Return items created before certain date/time (in UTC) (optional)
     * @param  \DateTime $created_on_or_after Format - date-time (as date-time in RFC3339). Return items created on or after certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_before Format - date-time (as date-time in RFC3339). Return items modified before certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_on_or_after Format - date-time (as date-time in RFC3339). Return items modified on or after certain date/time (in UTC) (optional)
     * @param  int $page Format - int32. The logical number of page to return, starting from 1 (optional)
     * @param  int $page_size Format - int32. How many records to return (50 by default) (optional)
     * @param  bool $include_total Whether total count should be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsGetListAsyncWithHttpInfo($tenant, $ids = null, $customer_ids = null, $active = null, $status = null, $duration = null, $billing_frequency = null, $created_before = null, $created_on_or_after = null, $modified_before = null, $modified_on_or_after = null, $page = null, $page_size = null, $include_total = null)
    {
        $returnType = '\CompWright\ServiceTitan\Model\PaginatedResponseOfMembershipsV2CustomerMembershipResponse';
        $request = $this->customerMembershipsGetListRequest($tenant, $ids, $customer_ids, $active, $status, $duration, $billing_frequency, $created_before, $created_on_or_after, $modified_before, $modified_on_or_after, $page, $page_size, $include_total);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerMembershipsGetList'
     *
     * @param  int $tenant Tenant ID (required)
     * @param  string $ids Perform lookup by multiple IDs (maximum 50) (optional)
     * @param  string $customer_ids Filters by customer IDs (optional)
     * @param  OneOfActiveQueryFilter $active What kind of items should be returned (only active items will be returned by default)\\ Values: [True, Any, False] (optional)
     * @param  OneOfMembershipsV2MembershipStatus $status Filters by membership status\\ Values: [Active, Suspended, Expired, Canceled, Deleted] (optional)
     * @param  int $duration Format - int32. Filters by membership duration (in months); use null for ongoing memberships (optional)
     * @param  OneOfMembershipsV2MembershipRecurrenceType $billing_frequency Filters by membership billing frequency\\ Values: [OneTime, Monthly, EveryOtherMonth, Quarterly, BiAnnual, Annual] (optional)
     * @param  \DateTime $created_before Format - date-time (as date-time in RFC3339). Return items created before certain date/time (in UTC) (optional)
     * @param  \DateTime $created_on_or_after Format - date-time (as date-time in RFC3339). Return items created on or after certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_before Format - date-time (as date-time in RFC3339). Return items modified before certain date/time (in UTC) (optional)
     * @param  \DateTime $modified_on_or_after Format - date-time (as date-time in RFC3339). Return items modified on or after certain date/time (in UTC) (optional)
     * @param  int $page Format - int32. The logical number of page to return, starting from 1 (optional)
     * @param  int $page_size Format - int32. How many records to return (50 by default) (optional)
     * @param  bool $include_total Whether total count should be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerMembershipsGetListRequest($tenant, $ids = null, $customer_ids = null, $active = null, $status = null, $duration = null, $billing_frequency = null, $created_before = null, $created_on_or_after = null, $modified_before = null, $modified_on_or_after = null, $page = null, $page_size = null, $include_total = null)
    {
        // verify the required parameter 'tenant' is set
        if ($tenant === null || (is_array($tenant) && count($tenant) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant when calling customerMembershipsGetList'
            );
        }

        $resourcePath = '/tenant/{tenant}/memberships';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($ids !== null) {
            if('form' === 'form' && is_array($ids)) {
                foreach($ids as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['ids'] = $ids;
            }
        }
        // query params
        if ($customer_ids !== null) {
            if('form' === 'form' && is_array($customer_ids)) {
                foreach($customer_ids as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['customerIds'] = $customer_ids;
            }
        }
        // query params
        if ($active !== null) {
            if('form' === 'form' && is_array($active)) {
                foreach($active as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['active'] = $active;
            }
        }
        // query params
        if ($status !== null) {
            if('form' === 'form' && is_array($status)) {
                foreach($status as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['status'] = $status;
            }
        }
        // query params
        if ($duration !== null) {
            if('form' === 'form' && is_array($duration)) {
                foreach($duration as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['duration'] = $duration;
            }
        }
        // query params
        if ($billing_frequency !== null) {
            if('form' === 'form' && is_array($billing_frequency)) {
                foreach($billing_frequency as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['billingFrequency'] = $billing_frequency;
            }
        }
        // query params
        if ($created_before !== null) {
            if('form' === 'form' && is_array($created_before)) {
                foreach($created_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['createdBefore'] = $created_before;
            }
        }
        // query params
        if ($created_on_or_after !== null) {
            if('form' === 'form' && is_array($created_on_or_after)) {
                foreach($created_on_or_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['createdOnOrAfter'] = $created_on_or_after;
            }
        }
        // query params
        if ($modified_before !== null) {
            if('form' === 'form' && is_array($modified_before)) {
                foreach($modified_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modifiedBefore'] = $modified_before;
            }
        }
        // query params
        if ($modified_on_or_after !== null) {
            if('form' === 'form' && is_array($modified_on_or_after)) {
                foreach($modified_on_or_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modifiedOnOrAfter'] = $modified_on_or_after;
            }
        }
        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }
        // query params
        if ($page_size !== null) {
            if('form' === 'form' && is_array($page_size)) {
                foreach($page_size as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['pageSize'] = $page_size;
            }
        }
        // query params
        if ($include_total !== null) {
            if('form' === 'form' && is_array($include_total)) {
                foreach($include_total as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['includeTotal'] = $include_total;
            }
        }


        // path params
        if ($tenant !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant' . '}',
                ObjectSerializer::toPathValue($tenant),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('ST-App-Key');
        if ($apiKey !== null) {
            $headers['ST-App-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('servicetitanapplicationkey');
        if ($apiKey !== null) {
            $queryParams['servicetitanapplicationkey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerMembershipsUpdate
     *
     * Updates specified customer membership in \&quot;patch\&quot; mode
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipUpdateRequest $memberships_v2_customer_membership_update_request Customer membership update request (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CompWright\ServiceTitan\Model\ModificationResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse
     */
    public function customerMembershipsUpdate($id, $tenant, $memberships_v2_customer_membership_update_request = null)
    {
        list($response) = $this->customerMembershipsUpdateWithHttpInfo($id, $tenant, $memberships_v2_customer_membership_update_request);
        return $response;
    }

    /**
     * Operation customerMembershipsUpdateWithHttpInfo
     *
     * Updates specified customer membership in \&quot;patch\&quot; mode
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipUpdateRequest $memberships_v2_customer_membership_update_request Customer membership update request (optional)
     *
     * @throws \CompWright\ServiceTitan\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CompWright\ServiceTitan\Model\ModificationResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse|\CompWright\ServiceTitan\Model\ApiErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerMembershipsUpdateWithHttpInfo($id, $tenant, $memberships_v2_customer_membership_update_request = null)
    {
        $request = $this->customerMembershipsUpdateRequest($id, $tenant, $memberships_v2_customer_membership_update_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\CompWright\ServiceTitan\Model\ModificationResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ModificationResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\CompWright\ServiceTitan\Model\ApiErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CompWright\ServiceTitan\Model\ApiErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CompWright\ServiceTitan\Model\ModificationResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ModificationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CompWright\ServiceTitan\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation customerMembershipsUpdateAsync
     *
     * Updates specified customer membership in \&quot;patch\&quot; mode
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipUpdateRequest $memberships_v2_customer_membership_update_request Customer membership update request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsUpdateAsync($id, $tenant, $memberships_v2_customer_membership_update_request = null)
    {
        return $this->customerMembershipsUpdateAsyncWithHttpInfo($id, $tenant, $memberships_v2_customer_membership_update_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerMembershipsUpdateAsyncWithHttpInfo
     *
     * Updates specified customer membership in \&quot;patch\&quot; mode
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipUpdateRequest $memberships_v2_customer_membership_update_request Customer membership update request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerMembershipsUpdateAsyncWithHttpInfo($id, $tenant, $memberships_v2_customer_membership_update_request = null)
    {
        $returnType = '\CompWright\ServiceTitan\Model\ModificationResponse';
        $request = $this->customerMembershipsUpdateRequest($id, $tenant, $memberships_v2_customer_membership_update_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerMembershipsUpdate'
     *
     * @param  int $id Format - int64. Customer membership ID (required)
     * @param  int $tenant Tenant ID (required)
     * @param  \CompWright\ServiceTitan\Model\MembershipsV2CustomerMembershipUpdateRequest $memberships_v2_customer_membership_update_request Customer membership update request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerMembershipsUpdateRequest($id, $tenant, $memberships_v2_customer_membership_update_request = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling customerMembershipsUpdate'
            );
        }
        // verify the required parameter 'tenant' is set
        if ($tenant === null || (is_array($tenant) && count($tenant) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant when calling customerMembershipsUpdate'
            );
        }

        $resourcePath = '/tenant/{tenant}/memberships/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($tenant !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant' . '}',
                ObjectSerializer::toPathValue($tenant),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($memberships_v2_customer_membership_update_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($memberships_v2_customer_membership_update_request));
            } else {
                $httpBody = $memberships_v2_customer_membership_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('ST-App-Key');
        if ($apiKey !== null) {
            $headers['ST-App-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('servicetitanapplicationkey');
        if ($apiKey !== null) {
            $queryParams['servicetitanapplicationkey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
