<?php
/**
 * InvoicesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for invoicesCreateAdjustmentInvoice
     *
     * create adjustment invoice.
     *
     */
    public function testInvoicesCreateAdjustmentInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesDeleteInvoiceItem
     *
     * delete invoice item.
     *
     */
    public function testInvoicesDeleteInvoiceItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesGetList
     *
     * Gets a list of invoices.
     *
     */
    public function testInvoicesGetList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesMarkAsExported
     *
     * mark invoice as exported. Id = invoiceId.
     *
     */
    public function testInvoicesMarkAsExported()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesUpdateCustomFields
     *
     * Updates custom fields for specified invoices.
     *
     */
    public function testInvoicesUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesUpdateInvoice
     *
     * update invoice.
     *
     */
    public function testInvoicesUpdateInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesUpdateInvoiceItems
     *
     * update invoice items.
     *
     */
    public function testInvoicesUpdateInvoiceItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
